default: &default
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: airwaze_mvp_development
  pool: 5

test:
  <<: *default
  database: airwaze_mvp_test

production:
  <<: *default
  database: airwaze_mvp_production
