<<<<<<< HEAD
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7d804cf2d1a3637c3c566b867ff1818f9bccba7d4d6e6aa5e7fe0c34bd50bf331b6e2238552323a5ffd63a6720b972102daab12aee762de101c467160ca5f00

test:
  secret_key_base: b401b9f21ca1c7cdf096226786335673902daf418c5b691a0a71c96a614088941c95145dfbcbc9f2bc1a5e3de5d2491611a0e45aee75012a41d00b3ca5548f18

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
=======
default: &default
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>

development:
  <<: *default
  secret_key_base: e7d804cf2d1a3637c3c566b867ff1818f9bccba7d4d6e6aa5e7fe0c34bd50bf331b6e2238552323a5ffd63a6720b972102daab12aee762de101c467160ca5f00

test:
  <<: *default
  secret_key_base: b401b9f21ca1c7cdf096226786335673902daf418c5b691a0a71c96a614088941c95145dfbcbc9f2bc1a5e3de5d2491611a0e45aee75012a41d00b3ca5548f18

production:
  <<: *default
>>>>>>> airwaze-mvp/master
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
